# Generated by Django 3.1.5 on 2021-03-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210304_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
